### PR TITLE
New Workflow, Version Plugin, and PlayerTools Plugin

### PR DESCRIPTION
**Pull request by KKonaOG**
GitHub Action Changes:
- npm run build:prod

Workflow Changes:
- Two different build types (npm run build:prod) and (npm run build:dev)
- Build Production Increments Version Number on Build (Requires Git State to be clean)
- Build Development Builds a slightly less minimized version (Similar to what we had before)

New Plugins:
- Version Plugin: Simply places the current GenLite Version next to Client Version on homepage
- PlayerTools Plugin: Shows player nameplates(tags) above their heads. I hope to find a way to hide the current player in the future. 

Changes:

- Fonts for Highlight Plugins are now the same as the game font
- XP Plugin now puts commas on all outputs (excluding times)

### CODE REVIEW

**Comment by dpeGit** [comment]
Can you also include the auto version bump on the readme.

**Comment by dpeGit** [comment]
For hiding the player just always filter out the currently player's id `PLAYER.id`

**Comment by KKonaOG** [comment]
> Can you also include the auto version bump on the readme.

Done

**Comment by KKonaOG** [comment]
> For hiding the player just always filter out the currently player's id `PLAYER.id`

Clarified as a different feature. That different feature is now implemented.

**Review by dpeGit — APPROVED** [review]

**Comment by dpeGit** [comment]
The pipeline doesn't seem to like the work flow change.

**Comment by dpeGit** [comment]
Okay this will be merged after the licensing update

**Pull request merged**
